// AUTH
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT_SUCCESS'

// MESSAGE
export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const GET_ERRORS = 'GET_ERRORS'

// CATALOG
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED'

// MODAL
export const OPEN_CART = 'OPEN_CART'
export const CLOSE_CART = 'CLOSE_MODAL' 
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'

// COMMENTS
export const GET_COMMENTS = 'GET_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'